/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const languages = [
  { code: "EN", name: "English" },
  { code: "ES", name: "Espanol" },
  { code: "FR", name: "Francais" },
  { code: "DE", name: "Deutsch" },
  { code: "PT", name: "Portugues" },
  { code: "ZH", name: "Chinese" },
  { code: "AR", name: "Arabic" },
];

const base = {
  signIn: "Sign In",
  signingIn: "Signing In...",
  voterAccess: "Voter Access",
  administrator: "Administrator",
  secretCode: "Secret Code",
  username: "Username",
  password: "Password",
  welcome: "Welcome",
  activeElections: "Active Elections",
  pastElections: "Past Elections",
  voteNow: "Vote Now",
  signOut: "Sign Out",
  profile: "Profile",
  language: "Language",
  voterManagement: "Voter Management",
  manageVoterCredentials: "Create, verify, and manage voter access credentials.",
  addVoter: "Add Voter",
  importCsv: "Import CSV",
  searchVoters: "Search voters...",
  totalVoters: "Total Voters",
  verified: "Verified",
  pending: "Pending",
  selectedVoters: "selected voters",
  deleteSelected: "Delete Selected",
  name: "Name",
  phone: "Phone",
  status: "Status",
  actions: "Actions",
  completed: "Completed",
  totalVotes: "Total Votes",
  accountStatus: "Account Status",
  selectCandidate: "Select Candidate",
  votes: "votes",
  cancel: "Cancel",
  castVote: "Cast Vote",
  castingVote: "Casting Vote...",
  voted: "Voted",
  dashboard: "Dashboard",
  elections: "Elections",
  candidates: "Candidates",
  voters: "Voters",
  voterCards: "Voter Cards",
  results: "Results",
  settings: "Settings",
};

const dictionary = {
  EN: base,
  ES: {
    ...base,
    signIn: "Iniciar sesion",
    signingIn: "Iniciando...",
    voterAccess: "Acceso votante",
    administrator: "Administrador",
    secretCode: "Codigo secreto",
    username: "Usuario",
    password: "Contrasena",
    welcome: "Bienvenido",
    activeElections: "Elecciones activas",
    pastElections: "Elecciones anteriores",
    voteNow: "Votar ahora",
    signOut: "Cerrar sesion",
    profile: "Perfil",
    language: "Idioma",
    voterManagement: "Gestion de votantes",
    manageVoterCredentials: "Cree, verifique y administre credenciales de votantes.",
    addVoter: "Agregar votante",
    importCsv: "Importar CSV",
    searchVoters: "Buscar votantes...",
    totalVoters: "Total de votantes",
    verified: "Verificado",
    pending: "Pendiente",
    selectedVoters: "votantes seleccionados",
    deleteSelected: "Eliminar seleccionados",
    name: "Nombre",
    phone: "Telefono",
    status: "Estado",
    actions: "Acciones",
    completed: "Completado",
    totalVotes: "Votos totales",
    accountStatus: "Estado de cuenta",
    selectCandidate: "Seleccione candidato",
    votes: "votos",
    cancel: "Cancelar",
    castVote: "Votar",
    castingVote: "Votando...",
    dashboard: "Panel",
    elections: "Elecciones",
    voters: "Votantes",
    voterCards: "Tarjetas de votante",
    results: "Resultados",
    settings: "Configuracion",
  },
  FR: {
    ...base,
    signIn: "Se connecter",
    signingIn: "Connexion...",
    voterAccess: "Acces electeur",
    administrator: "Administrateur",
    secretCode: "Code secret",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    welcome: "Bienvenue",
    activeElections: "Elections actives",
    pastElections: "Elections passees",
    voteNow: "Voter",
    signOut: "Deconnexion",
    profile: "Profil",
    language: "Langue",
    voterManagement: "Gestion des electeurs",
    manageVoterCredentials: "Creez, verifiez et gerez les identifiants des electeurs.",
    addVoter: "Ajouter electeur",
    importCsv: "Importer CSV",
    searchVoters: "Rechercher des electeurs...",
    totalVoters: "Total electeurs",
    verified: "Verifie",
    pending: "En attente",
    selectedVoters: "electeurs selectionnes",
    deleteSelected: "Supprimer selection",
    name: "Nom",
    phone: "Telephone",
    status: "Statut",
    actions: "Actions",
    completed: "Termine",
    totalVotes: "Votes totaux",
    accountStatus: "Statut du compte",
    selectCandidate: "Choisir candidat",
    votes: "votes",
    cancel: "Annuler",
    castVote: "Voter",
    castingVote: "Vote...",
    dashboard: "Tableau",
    elections: "Elections",
    voters: "Electeurs",
    voterCards: "Cartes electeur",
    results: "Resultats",
    settings: "Parametres",
  },
  DE: {
    ...base,
    signIn: "Anmelden",
    signingIn: "Anmeldung...",
    voterAccess: "Wahlerzugang",
    administrator: "Administrator",
    secretCode: "Geheimcode",
    username: "Benutzername",
    password: "Passwort",
    welcome: "Willkommen",
    activeElections: "Aktive Wahlen",
    pastElections: "Vergangene Wahlen",
    voteNow: "Jetzt wahlen",
    signOut: "Abmelden",
    profile: "Profil",
    language: "Sprache",
    voterManagement: "Wahlerverwaltung",
    addVoter: "Wahler hinzufugen",
    importCsv: "CSV importieren",
    searchVoters: "Wahler suchen...",
    totalVoters: "Wahler gesamt",
    verified: "Verifiziert",
    pending: "Ausstehend",
    selectedVoters: "ausgewahlte Wahler",
    deleteSelected: "Auswahl loschen",
    name: "Name",
    phone: "Telefon",
    status: "Status",
    actions: "Aktionen",
    completed: "Abgeschlossen",
    totalVotes: "Stimmen gesamt",
    accountStatus: "Kontostatus",
    selectCandidate: "Kandidat auswahlen",
    votes: "Stimmen",
    cancel: "Abbrechen",
    castVote: "Stimme abgeben",
    castingVote: "Stimme wird abgegeben...",
    dashboard: "Dashboard",
    elections: "Wahlen",
    voters: "Wahler",
    voterCards: "Wahlerkarten",
    results: "Ergebnisse",
    settings: "Einstellungen",
  },
  PT: {
    ...base,
    signIn: "Entrar",
    signingIn: "Entrando...",
    voterAccess: "Acesso do eleitor",
    administrator: "Administrador",
    secretCode: "Codigo secreto",
    username: "Usuario",
    password: "Senha",
    welcome: "Bem-vindo",
    activeElections: "Eleicoes ativas",
    pastElections: "Eleicoes passadas",
    voteNow: "Votar agora",
    signOut: "Sair",
    profile: "Perfil",
    language: "Idioma",
    voterManagement: "Gestao de eleitores",
    addVoter: "Adicionar eleitor",
    importCsv: "Importar CSV",
    searchVoters: "Pesquisar eleitores...",
    totalVoters: "Total de eleitores",
    verified: "Verificado",
    pending: "Pendente",
    selectedVoters: "eleitores selecionados",
    deleteSelected: "Excluir selecionados",
    name: "Nome",
    phone: "Telefone",
    status: "Status",
    actions: "Acoes",
    completed: "Concluido",
    totalVotes: "Votos totais",
    accountStatus: "Status da conta",
    selectCandidate: "Selecionar candidato",
    votes: "votos",
    cancel: "Cancelar",
    castVote: "Votar",
    castingVote: "Votando...",
    dashboard: "Painel",
    elections: "Eleicoes",
    voters: "Eleitores",
    voterCards: "Cartoes de eleitor",
    results: "Resultados",
    settings: "Configuracoes",
  },
  ZH: {
    ...base,
    signIn: "Sign In",
    voterAccess: "Voter Access",
    administrator: "Administrator",
    welcome: "Welcome",
    voteNow: "Vote Now",
    signOut: "Sign Out",
    language: "Language",
  },
  AR: {
    ...base,
    signIn: "Sign In",
    voterAccess: "Voter Access",
    administrator: "Administrator",
    welcome: "Welcome",
    voteNow: "Vote Now",
    signOut: "Sign Out",
    language: "Language",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem("securevote_language") || "EN");

  useEffect(() => {
    localStorage.setItem("securevote_language", language);
  }, [language]);

  const value = useMemo(() => {
    const translate = (key) => dictionary[language]?.[key] || dictionary.EN[key] || key;
    return { language, setLanguage, languages, t: translate };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
};
